######################################################################
# Automatically generated by qmake (2.01a) Mon Apr 29 02:25:51 2013
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
SOURCES += main.cpp
