######################################################################
# Automatically generated by qmake (2.01a) Mon Apr 29 03:08:30 2013
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
FORMS += main.ui
SOURCES += main.cpp
